#%RAML 1.0 Library

resourceTypes:
  - collection:

  - collectionItem:

traits:

  pageable:
    queryParameters:
      offset:
        description: Skip over a number of elements by specifying an offset value for the query
        type: number
        format: int32
        required: false
        example: 20
        default: 0
      limit:
        description: Limit the number of elements on the response
        type: number
        format: int32
        required: false
        example: 80
        default: 10
    responses:
      200:
        headers:
          X-Total-Count:
            description: Total count of resources in the list.
            type: number
            format: int32
            required: true
          Links:
            description: |
              Links to the following and last page of the list
              formated according to the [RFC 5988](https://tools.ietf.org/html/rfc5988#page-6).
            type: string
